### ISSUE TITLE
devブランチ作った方がいい？

### ISSUE THREAD

**Issue by MinamiInoue2323** [MinamiInoue2323/osoji_kun#62]
今直接mainにpushしてるけど、vercelにデプロイされるようにしたからdevelopブランチみたいな開発用のやつ作った方がいい？
問題なければcloseしてもらって大丈夫です。

**Comment by kyuki3rain** [comment]
作った方がいいと思うので、適当にブランチ切ってpushしてください。

ついでに、mainへの直接のPushを禁止する設定があるので、これをやってみて！！！
https://zenn.dev/norikt/articles/7c41c723e64eaf

**Comment by MinamiInoue2323** [comment]
- developブランチ作りました！
- require approvalって項目がデフォルトでつくんだけど、リンクのやつでは消してたので今回はなしで登録しました

**Comment by kyuki3rain** [comment]
default Branchをdevelopに変更して、mainブランチにPull Request必須（Require a pull request before merging）のBranch protection ruleを付けるとよさそうです。

Require Approvalは、ほんとにチーム開発するならあった方がいいけど、自分だけでマージできなくなるので個人開発だと不便。でも、どのみち管理者はルールを踏み倒せるので、あんまり気にしなくて大丈夫です。

**Comment by MinamiInoue2323** [comment]
default branchをdevelopに変更しました！
Branch protection ruleは前回つけたので問題なさそうなのでそのままにしてあります。

**Comment by kyuki3rain** [comment]
👍
