### ISSUE TITLE
Projectsを作る

### ISSUE THREAD

**Issue by kyuki3rain** [MinamiInoue2323/osoji_kun#63]

**Comment by kyuki3rain** [comment]
このページのProjectsというところから、Projectsを作って見てください。

この時、設定をKanbanにしておけば、スクラム開発体験ぽいことできると思う！

**Comment by kyuki3rain** [comment]
とりあえずProjectsは作るだけでいいです。触ってあそんでみてもよい。

**Comment by kyuki3rain** [comment]
https://github.com/users/kyuki3rain/projects/5/views/1

こんな感じになるよ！

**Comment by MinamiInoue2323** [comment]
作ってみたー！
これってリポジトリと紐付けできる？
https://github.com/users/MinamiInoue2323/projects/1/views/1

**Comment by kyuki3rain** [comment]
このリポジトリのタブの中にprojectsがあって、link a project ってボタンがあるから、そこから行けそう？

こちらからそのリンクも見れてないので、権限回りも見直してみてください！（もしかしたらリポジトリと紐づけたら一緒に共有されるかも？）

**Comment by MinamiInoue2323** [comment]
projectとは紐づけられてるっぽい（リポジトリのprojectのところ押したら出てくる）
権限修正したので見れると思います。確認お願いします！

**Comment by kyuki3rain** [comment]
👍
