### ISSUE TITLE
stateの永続化

### ISSUE THREAD

**Issue by kyuki3rain** [MinamiInoue2323/osoji_kun#64]
- `currentTargetPlaceState`
- `finishPlaceListState`
- `placeListState`

を永続化（リロードしてもデータが残っている状態）してください！

**Comment by kyuki3rain** [comment]
recoil-persistとか使うのがよさそうです！

**Comment by MinamiInoue2323** [comment]
参考：https://qiita.com/zaburo/items/e28be44f6b98e36b38c7#recoilの永続化
