### ISSUE TITLE
firebase authの追加

### ISSUE THREAD

**Issue by kyuki3rain** [MinamiInoue2323/osoji_kun#67]
firebase authentificationの機能を追加してみましょう。

## やりたいこと
このアプリに認証機能を追加する

## ゴール
- ログインページの追加
- ログインが必要な画面（今回はログインページ以外のすべて）でログインしているかどうかを判別
  - してなかったらログインページに飛ばす
- ログインしていたらヘッダー右上にログアウトボタンを出す
  -  ここはいったん「Logoutという文字が直置きされてそれを押すとログアウト」くらいの仮実装で大丈夫！
  - 最終的には、丸く切り取られたAvaterがあって、それを押すとユーザーページにとんで、そこにログアウトボタンがある、みたいな実装をやるとよい気がしますが、別タスクでも可

## 注意点
- firebaseConfigの中身は、基本的に環境変数にする方がよいです（結局フロントで動かすからどうせ頑張ればばれちゃうものなんだけど、一応）
- 環境変数にした場合、Vercel上でも設定してあげる必要があります

## 参考
この記事とか使って、今のコードとうまくつなげられるように調整しながら作ってみてください。
https://tech-lab.sios.jp/archives/33027

かなり誘導少な目のタスクなのと、認証周りは本当にストレスがたまるので、詰まったら聞く！またはいったん時間を空ける！が大事です。
通話できるときにやってもいいかも。

**Comment by kyuki3rain** [comment]
参考
https://www.mizdra.net/entry/2019/09/07/123437

**Comment by MinamiInoue2323** [comment]
vercel上での環境変数の設定も行いました（development, previewのみ）
firebase上での許可をどの様な形にしようか迷っているので相談したいです
