### ISSUE TITLE
developブランチのpreviewページをfirebaseに登録する

### ISSUE THREAD

**Issue by kyuki3rain** [MinamiInoue2323/osoji_kun#83]
完全に忘れてたけど、特定のブランチのpreviewページはURLが固定になるので、firebaseに認証済みドメインとして登録できると思う！

ということで、`https://osoji-kun-git-develop-minamiinoue2323.vercel.app/`をauthorized Domainに登録してほしいです！

**Comment by MinamiInoue2323** [comment]
登録しました！

**Comment by kyuki3rain** [comment]
ありがたや！！！
